/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../pages/__root'
import { Route as RoomRouteImport } from './../pages/room'
import { Route as BoardRouteImport } from './../pages/board'
import { Route as AuthenticatedRouteImport } from './../pages/_authenticated'
import { Route as IndexRouteImport } from './../pages/index'
import { Route as ProjectsProjectIdRouteImport } from './../pages/projects/$projectId'
import { Route as AuthLoginRouteImport } from './../pages/auth/login'
import { Route as AuthJoinRouteRouteImport } from './../pages/auth/join/route'
import { Route as AuthJoinSuccessRouteImport } from './../pages/auth/join/success'

const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthJoinRouteRoute = AuthJoinRouteRouteImport.update({
  id: '/auth/join',
  path: '/auth/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthJoinSuccessRoute = AuthJoinSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AuthJoinRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/room': typeof RoomRoute
  '/auth/join': typeof AuthJoinRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/auth/join/success': typeof AuthJoinSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/room': typeof RoomRoute
  '/auth/join': typeof AuthJoinRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/auth/join/success': typeof AuthJoinSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/board': typeof BoardRoute
  '/room': typeof RoomRoute
  '/auth/join': typeof AuthJoinRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/auth/join/success': typeof AuthJoinSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/room'
    | '/auth/join'
    | '/auth/login'
    | '/projects/$projectId'
    | '/auth/join/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/room'
    | '/auth/join'
    | '/auth/login'
    | '/projects/$projectId'
    | '/auth/join/success'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/board'
    | '/room'
    | '/auth/join'
    | '/auth/login'
    | '/projects/$projectId'
    | '/auth/join/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  BoardRoute: typeof BoardRoute
  RoomRoute: typeof RoomRoute
  AuthJoinRouteRoute: typeof AuthJoinRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/join': {
      id: '/auth/join'
      path: '/auth/join'
      fullPath: '/auth/join'
      preLoaderRoute: typeof AuthJoinRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/join/success': {
      id: '/auth/join/success'
      path: '/success'
      fullPath: '/auth/join/success'
      preLoaderRoute: typeof AuthJoinSuccessRouteImport
      parentRoute: typeof AuthJoinRouteRoute
    }
  }
}

interface AuthJoinRouteRouteChildren {
  AuthJoinSuccessRoute: typeof AuthJoinSuccessRoute
}

const AuthJoinRouteRouteChildren: AuthJoinRouteRouteChildren = {
  AuthJoinSuccessRoute: AuthJoinSuccessRoute,
}

const AuthJoinRouteRouteWithChildren = AuthJoinRouteRoute._addFileChildren(
  AuthJoinRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  BoardRoute: BoardRoute,
  RoomRoute: RoomRoute,
  AuthJoinRouteRoute: AuthJoinRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
